import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "@/app/components/QueryProvider";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Job Listing App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <QueryProvider>
            <main>
              {children}
              <ReactQueryDevtools initialIsOpen={false} />
            </main>
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
